=== FranciscoFreitas45/DAW/DWeb2019/TP2/PR.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT PR (record,header,workteam,abstract,deliverables,date)>
<!ELEMENT record (#PCDATA) >
<!ELEMENT header ( key-name,title,subtitle,begin-date,end-date,supervisor)>
<!ELEMENT key-name (#PCDATA) >
<!ELEMENT title (#PCDATA) >
<!ELEMENT subtitle (#PCDATA) >
<!ELEMENT begin-date (#PCDATA) >
<!ELEMENT end-date (#PCDATA) >
<!ELEMENT supervisor (#PCDATA) >
<!ATTLIST supervisor 
                  href  CDATA #REQUIRED>
<!ELEMENT workteam (person+) >
<!ELEMENT person (name,number,email,github?) >
<!ELEMENT name (#PCDATA) >
<!ELEMENT number (#PCDATA) >
<!ELEMENT email ( #PCDATA)>
<!ELEMENT github (#PCDATA) >
<!ATTLIST github 
                href CDATA #REQUIRED>
<!ELEMENT abstract (paragraph+) >
<!ELEMENT paragraph (#PCDATA|b|i|link)* >
<!ELEMENT b (#PCDATA|i|link)* >
<!ELEMENT i (#PCDATA|b|link)* >
<!ELEMENT link (#PCDATA) >
<!ATTLIST link
          href CDATA #REQUIRED>
<!ELEMENT deliverables (deliverable+) >
<!ELEMENT deliverable (#PCDATA) >
<!ATTLIST deliverable  
           href CDATA #REQUIRED >
                  
<!ELEMENT date (#PCDATA) >

=== FranciscoFreitas45/DAW/DWeb2019/TP2/PR.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE PR SYSTEM "PR.dtd">
<PR>
    <record>TPC Record</record>
    <header>
        <key-name>TPC2</key-name>
        <title>Processamento de Arqueossítios</title>
        <subtitle>Aprofundamento de conhecimentos sobre XML,DTD e XPath</subtitle>
        <begin-date>24/09/2019</begin-date>
        <end-date>01/10/2019</end-date>
        <supervisor href="http://www4.di.uminho.pt/~jcr/">José Carlos Ramalho </supervisor>
    </header>
    <workteam>
        <person>
            <name>Francisco Freitas</name>
            <number>A81580</number>
            <email>zefreitas2011@hotmail.com</email>
            <github href="https://github.com/FranciscoFreitas45">github</github>
        </person>
    </workteam>
    <abstract>
        <paragraph>Este trabalho foi dividio em 2 partes. </paragraph>
        <paragraph>A 1ª parte consistia na criação de um <b>DTD<i>(Document Type Definition)</i></b>com base no seguinte 
            <link href="http://www4.di.uminho.pt/~jcr/XML/didac/xmldocs/PR.htm">documento</link>
        </paragraph>
        <paragraph>A 2ª parte consistia na resolução de 2 exercicios da  <link href="http://www4.di.uminho.pt/~jcr/XML/CURSOS/PED2008/fichas/ficha3/">ficha 3 </link> <i>(Exercicios 6 e 7)</i>.</paragraph>
        <paragraph>O exercicio 6 consistia em escrever espressões XPath para o seguinte 
            <link href="http://www4.di.uminho.pt/~jcr/XML/didac/xmldocs/arq.xml">documento XML</link>
            e o exercicio 7 na resolucão de DTD para o mesmo documento.
        </paragraph>
    </abstract>
    <deliverables>
        <deliverable href="https://github.com/FranciscoFreitas45/DAW/blob/master/DWeb2019/TP2/PR.dtd">PR(DTD) </deliverable>
        <deliverable href="https://github.com/FranciscoFreitas45/DAW/blob/master/DWeb2019/TP2/PR.xml">PR(XML)</deliverable>
        <deliverable href="https://github.com/FranciscoFreitas45/DAW/blob/master/DWeb2019/TP2/ficha3ex7.txt">Arqueossítios(XPath)</deliverable>
        <deliverable href="https://github.com/FranciscoFreitas45/DAW/blob/master/DWeb2019/TP2/ARQSITS.dtd">Arqueossítios(DTD)</deliverable>
    </deliverables>
    <date>01/10/2019</date>
</PR>
